
CREATE TABLE [dbo].[Goal](
	[Id] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Goal_Id]  DEFAULT (newid()),
	[Name] [varchar](500) NOT NULL,
	[Description] [varchar](2500) NOT NULL,
 CONSTRAINT [PK_Goal] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

